=== AlexanderDashkov/BlameInspector/BlameInspector/projects.xsd
<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="projects">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="project" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="project">
    <xs:complexType>
       <xs:sequence>
        <xs:element name="vcs">
         <xs:simpleType final="restriction">
          <xs:restriction base="xs:string">
            <xs:enumeration value="git"/>
            <xs:enumeration value="svn"/>
           </xs:restriction>
         </xs:simpleType>
        </xs:element>
        <xs:element name="pathToRepo" type="xs:string"/>
        <xs:element name="projectName" type="xs:string"/>
        <xs:element name="issueTracker" type="xs:string"/>
        <xs:element name="userName" type="xs:string"/>
        <xs:element name="password" type="xs:string"/>
       </xs:sequence>
     <xs:attribute name="name" type="xs:string"/>
    </xs:complexType>

  </xs:element>
</xs:schema>

=== AlexanderDashkov/BlameInspector/BlameInspector/src/test/resources/schemas/positive/Long.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE projects>
<projects xsi:noNamespaceSchemaLocation="projects.xsd" 
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <project name="BlameWhoTest">
         <vcs>git</vcs>
         <pathToRepo>C:\Users\александр\Desktop\Jane's Repo\BlameWhoTest</pathToRepo>
         <projectName>BlameWhoTest</projectName>
         <issueTracker>https://github.com/JackSmithJunior/BlameWhoTest</issueTracker>
         <password>PASS</password>
         <userName>NAME</userName>
    </project>
    <project name="BlameBit">
         <vcs>git</vcs>
         <pathToRepo>C:\Users\александр\Desktop\JackBitRepo\blamebit</pathToRepo>
         <projectName>BlameBit</projectName>
         <issueTracker>https://bitbucket.org/JackSmithJunior/blamebit</issueTracker>
         <userName>NAMEr</userName>
         <password>PASS</password>
    </project>
    <project name="BlameSvn">
         <vcs>svn</vcs>
         <pathToRepo>C:\Users\александр\Desktop\guavaSvn\guava</pathToRepo>
         <projectName>guava</projectName>
         <issueTracker>https://github.com/google/guava</issueTracker>
         <userName>NAME</userName>
         <password>PASS</password>
    </project>
      <project name="Guava">
         <vcs>git</vcs>
         <pathToRepo>C:\Users\александр\Desktop\Google\guava</pathToRepo>
         <projectName>guava</projectName>
         <issueTracker>https://github.com/google/guava</issueTracker>
         <userName>NAME</userName>
         <password>PASS</password>
    </project>
    <project name="Kotlin">
         <vcs>git</vcs>
         <pathToRepo>C:\Users\александр\Desktop\Kotlin\kotlin</pathToRepo>
         <projectName>KT</projectName>
         <issueTracker>https://youtrack.jetbrains.com/issues/KT</issueTracker>
         <userName>NAME</userName>
         <password>PASS</password>
    </project>
</projects>
